# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MateRunner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  # test targets
  target 'RunningPreparationTests' do
    inherit! :search_paths
    pod 'RxTest'
  end
	target 'SingleRunningTests' do
    inherit! :search_paths
		pod 'RxTest'
	end
	target 'DistanceSettingTests' do
		inherit! :search_paths
		pod 'RxTest'
	end
end
