# Uncomment the next line to define a global platform for your project
inhibit_all_warnings!
platform :ios, '13.0'

target 'MateRunner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'SwiftLint'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '~> 8.0-beta'
  pod 'Firebase/Messaging'
  pod 'FirebaseUI/OAuth'
  # Pods for MateRunner
  target 'RunningPreparationTests' do
    inherit! :search_paths
    pod 'RxTest'
  end
  target 'SingleRunningTests' do
    inherit! :search_paths
    pod 'RxTest'
  end
  target 'DistanceSettingTests' do
    inherit! :search_paths
    pod 'RxTest'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
